Repository cossacklabs/themis, pull requests merged in 2019-12, with the labels that each got.

#559 Unbreak Doxygen configuration
  Doxyfile
  src/themis/secure_message.h
Labels: docs :books:

#560 Symmetric keygen: Themis Core
  CHANGELOG.md
  src/themis/secure_keygen.c
  src/themis/secure_keygen.h
  tests/themis/themis_secure_cell.c
Labels: core

#563 Make some JavaThemis exceptions unchecked
  CHANGELOG.md
  src/wrappers/themis/java/com/cossacklabs/themis/InvalidArgumentException.java
  src/wrappers/themis/java/com/cossacklabs/themis/KeyGenerationException.java
  src/wrappers/themis/java/com/cossacklabs/themis/KeypairGenerator.java
  src/wrappers/themis/java/com/cossacklabs/themis/NullArgumentException.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureCell.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureCompare.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureMessage.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureSession.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureTransportSession.java
Labels: W-JavaThemis :coffee:

#562 Symmetric keygen: JsThemis
  CHANGELOG.md
  src/wrappers/themis/jsthemis/addon.cpp
  src/wrappers/themis/jsthemis/secure_keygen.cpp
  src/wrappers/themis/jsthemis/secure_keygen.hpp
  tests/jsthemis/test.js
Labels: W-JsThemis :lollipop:

#564 Introduce common IKey interface
  CHANGELOG.md
  src/wrappers/themis/java/com/cossacklabs/themis/AsymmetricKey.java
  src/wrappers/themis/java/com/cossacklabs/themis/IKey.java
  src/wrappers/themis/java/com/cossacklabs/themis/KeyBytes.java
  src/wrappers/themis/java/com/cossacklabs/themis/PrivateKey.java
  src/wrappers/themis/java/com/cossacklabs/themis/PublicKey.java
Labels: W-JavaThemis :coffee:

#561 Symmetric keygen: high-level wrappers
  CHANGELOG.md
  gothemis/keys/symmetric.go
  gothemis/keys/symmetric_test.go
  src/wrappers/themis/Obj-C/objcthemis/skeygen.h
  src/wrappers/themis/Obj-C/objcthemis/skeygen.m
  src/wrappers/themis/php/php_themis.c
  src/wrappers/themis/php/php_themis.h
  src/wrappers/themis/php7/php_key_generator.c
  src/wrappers/themis/php7/php_key_generator.h
  src/wrappers/themis/php7/php_themis.c
  src/wrappers/themis/python/pythemis/skeygen.py
  src/wrappers/themis/ruby/lib/rbthemis.rb
  src/wrappers/themis/rust/CHANGELOG.md
  src/wrappers/themis/rust/src/keys.rs
  src/wrappers/themis/themispp/secure_keygen.hpp
  src/wrappers/themis/wasm/src/secure_keygen.js
  src/wrappers/themis/wasm/test/test.js
  tests/objcthemis/objthemis/SecureCellTests.m
  tests/objcthemis/objthemis/SecureCellTestsSwift.swift
  tests/phpthemis/scell_test.php
  tests/pythemis/test_skeygen.py
  tests/rbthemis/scell_test.rb
  tests/rust/keys.rs
  tests/themispp/secure_cell_test.hpp
Labels: W-GoThemis :hamster:, W-ObjCThemis :art:, W-PHPThemis :elephant:, W-PyThemis :snake:, W-RbThemis :diamonds:, W-RustThemis :crab:, W-SwiftThemis :large_orange_diamond:, W-ThemisPP :crossed_swords:, W-WasmThemis :globe_with_meridians:

#565 Symmetric keygen: JavaThemis
  CHANGELOG.md
  jni/themis_keygen.c
  src/wrappers/themis/java/com/cossacklabs/themis/KeyGenerationException.java
  src/wrappers/themis/java/com/cossacklabs/themis/KeypairGenerator.java
  src/wrappers/themis/java/com/cossacklabs/themis/SymmetricKey.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SymmetricKeyTest.java
Labels: W-JavaThemis :coffee:

#566 Update PHP Composer checksum
  tests/phpthemis/composer-setup.sh
Labels: W-PHPThemis :elephant:, infrastructure

#567 Fetch Composer SHA sum from GitHub
  tests/phpthemis/composer-setup.sh
Labels: W-PHPThemis :elephant:, infrastructure

#568 Try to make WebAssembly wrapper build work
  .gitignore
  src/wrappers/themis/wasm/README.md
  src/wrappers/themis/wasm/src/secure_cell_token_protect.js
Labels: W-WasmThemis :globe_with_meridians:

#569 Use "fastcomp" flavor of Emscripten
  .circleci/config.yml
Labels: W-WasmThemis :globe_with_meridians:, infrastructure

#571 Fix compatibility with Rust 1.40
  src/wrappers/themis/rust/libthemis-src/src/lib.rs
  tests/rust/run_tests.sh
Labels: W-RustThemis :crab:

#572 Run ThemisPP tests with C++14 and C++17
  .circleci/config.yml
  CHANGELOG.md
Labels: W-ThemisPP :crossed_swords:, infrastructure

#573 Run CircleCI builds every day
  .circleci/config.yml
Labels: infrastructure

#570 Always check soter_rand() for success
  .clang-tidy
  src/soter/soter_error.h
  src/soter/soter_rand.h
  src/wrappers/themis/themispp/secure_rand.hpp
  tests/common/test_utils.c
  tests/themispp/main.cpp
  tests/themispp/secure_rand_test.hpp
Labels: W-ThemisPP :crossed_swords:, core, tests
