Repository cossacklabs/themis, pull requests merged in 2019-09, with the labels that each got.

#523 Search build directory first when linking
  Makefile
  src/themis/themis.mk
Labels: core, infrastructure

#524 Plug leaks in RSA key imports
  src/soter/boringssl/soter_rsa_key.c
  src/soter/openssl/soter_rsa_key.c
Labels: core

#525 Avoid double-free errors in RSA key generation
  src/soter/boringssl/soter_rsa_common.c
  src/soter/openssl/soter_rsa_key_pair_gen.c
Labels: core

#527 Cleanup Makefile
  Makefile
  src/soter/soter.mk
  src/themis/themis.mk
  src/wrappers/themis/themispp/themispp.mk
  src/wrappers/themis/wasm/wasmthemis.mk
  tests/test.mk
Labels: infrastructure

#531 Update changelog for Themis 0.12.0
  CHANGELOG.md
Labels: docs

#535 Correct EVP_PKEY ownership
  src/soter/boringssl/soter_asym_cipher.c
  src/soter/boringssl/soter_asym_ka.c
  src/soter/boringssl/soter_ecdsa_common.c
  src/soter/boringssl/soter_rsa_key_pair_gen.c
  src/soter/boringssl/soter_sign_ecdsa.c
  src/soter/boringssl/soter_sign_rsa.c
  src/soter/boringssl/soter_verify_ecdsa.c
  src/soter/boringssl/soter_verify_rsa.c
  src/soter/openssl/soter_asym_cipher.c
  src/soter/openssl/soter_asym_ka.c
  src/soter/openssl/soter_rsa_key_pair_gen.c
  src/soter/openssl/soter_sign_ecdsa.c
  src/soter/openssl/soter_sign_rsa.c
  src/soter/openssl/soter_verify_ecdsa.c
  src/soter/openssl/soter_verify_rsa.c
  tests/soter/soter_asym_cipher_test.c
Labels: BoringSSL, OpenSSL, core

#537 Avoid duplicate header names
  Themis.xcodeproj/project.pbxproj
  src/soter/boringssl/soter_ec_key.c
  src/soter/boringssl/soter_rsa_key.c
  src/soter/openssl/soter_ec_key.c
  src/soter/openssl/soter_rsa_key.c
  src/soter/soter_container.c
  src/soter/soter_portable_endian.h
  src/themis/secure_keygen.c
  src/themis/secure_session.c
  src/themis/secure_session_message.c
  src/themis/secure_session_serialize.c
  src/themis/secure_session_utils.c
  src/themis/themis_portable_endian.h
Labels: core

#539 bump themis iOS to 0.12.2, update podspec, update examples
  docs/examples/Themis-server/Obj-C/Podfile
  docs/examples/Themis-server/Obj-C/Podfile.lock
  docs/examples/Themis-server/Obj-C/WorkingWithThemisServer/WorkingWithThemisServer.xcodeproj/project.pbxproj
  docs/examples/Themis-server/swift/Podfile
  docs/examples/Themis-server/swift/Podfile.lock
  docs/examples/Themis-server/swift/SwiftThemisServerExample/SwiftThemisServerExample.xcodeproj/project.pbxproj
  docs/examples/objc/iOS-CocoaPods/Podfile
  docs/examples/objc/iOS-CocoaPods/Podfile.lock
  docs/examples/objc/iOS-CocoaPods/ThemisTest/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-CocoaPods/Podfile
  docs/examples/swift/iOS-CocoaPods/Podfile.lock
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift.xcodeproj/project.pbxproj
  src/wrappers/themis/Obj-C/Themis/Info.plist
  themis.podspec
Labels: 📱 iOS

#541 Readme & Changelog 0.12.X
  CHANGELOG.md
  README.md
Labels: docs

#540 Fix warnings found by clang-tidy
  .circleci/config.yml
  .clang-tidy
  src/soter/boringssl/soter_ec_key.c
  src/soter/boringssl/soter_rsa_common.c
  src/soter/boringssl/soter_rsa_common.h
  src/soter/boringssl/soter_rsa_key.c
  src/soter/openssl/soter_ec_key.c
  src/soter/openssl/soter_rsa_key.c
  src/soter/soter_ec_key.h
  src/soter/soter_error.h
  src/soter/soter_kdf.c
  src/soter/soter_rsa_key.h
  src/soter/soter_sign.c
  src/soter/soter_t.h
  src/themis/secure_comparator.c
  src/themis/secure_message_wrapper.h
  src/themis/secure_session.c
  src/themis/secure_session_serialize.c
  src/themis/secure_session_utils.c
  src/themis/secure_session_utils.h
  src/wrappers/themis/jsthemis/.clang-tidy
  src/wrappers/themis/jsthemis/common.hpp
  src/wrappers/themis/jsthemis/secure_session.cpp
  src/wrappers/themis/jsthemis/secure_session.hpp
  src/wrappers/themis/themispp/secure_cell.hpp
  src/wrappers/themis/themispp/secure_comparator.hpp
  src/wrappers/themis/themispp/secure_keygen.hpp
  src/wrappers/themis/themispp/secure_message.hpp
  src/wrappers/themis/themispp/secure_session.hpp
  tests/common/sput.h
  tests/soter/soter_asym_cipher_test.c
  tests/soter/soter_hash_test.c
  tests/soter/soter_sym_test.c
  tests/themis/themis_seccure_message.c
  tests/themis/themis_secure_cell.c
  tests/themis/themis_secure_comparator.c
  tests/themis/themis_secure_session.c
  tests/themispp/main.cpp
  tests/themispp/secure_cell_test.hpp
  tests/themispp/secure_comparator_test.hpp
  tests/themispp/secure_message_test.hpp
  tests/themispp/secure_session_test.hpp
  tests/themispp/utils.hpp
Labels: W-JsThemis, W-ThemisPP, compatibility, core, next release
