Repository cossacklabs/themis, pull requests merged in 2019-10, with the labels that each got.

#546 Add a semantic patch to prevent use after free.
  scripts/cocci/null-after-free.cocci
  scripts/cocci/themis-free-functions.txt
  src/soter/soter_hmac.c
  src/themis/message.c
  src/themis/secure_message_wrapper.c
Labels: bug, core

#545 Avoid overflows in left shifts
  src/soter/soter_crc32.c
Labels: core

#543 Build with optimizations by default
  Makefile
Labels: infrastructure

#542 Correct recursive make invocation
  tools/afl/fuzzy.mk
Labels: infrastructure, tests

#550 Roll back to Emscripten 1.38.48
  .circleci/config.yml
Labels: W-WasmThemis :globe_with_meridians:, infrastructure
