Repository cossacklabs/themis, pull requests merged in 2019-04, with the labels that each got.

#442 Fix pkg-config packaging on Linux
  Makefile
Labels: infrastructure, installation

#443 Relax compatibility constraints
  src/wrappers/themis/rust/Cargo.toml
  src/wrappers/themis/rust/libthemis-sys/Cargo.toml
Labels: rust

#444 Try standard system path when pkg-config fails
  src/wrappers/themis/rust/CHANGELOG.md
  src/wrappers/themis/rust/libthemis-sys/build.rs
  src/wrappers/themis/rust/libthemis-sys/src/dummy.c
Labels: installation, rust

#445 Rust-Themis 0.11.1
  src/wrappers/themis/rust/CHANGELOG.md
  src/wrappers/themis/rust/Cargo.toml
  src/wrappers/themis/rust/libthemis-sys/Cargo.toml
Labels: rust

#446 Add libssl-dev/openssl-devel to the list of dev packages dependencies
  Makefile
Labels: infrastructure, installation

#447 Optimize embedded BoringSSL build
  src/soter/boringssl/soter.mk
  third_party/boringssl/build.gradle
Labels: android, boringssl, java

#450 Improve Makefile rules for linkage
  Makefile
  jni/themis_jni.mk
  src/soter/boringssl/soter.mk
  src/soter/openssl/soter.mk
  src/soter/soter.mk
  src/themis/themis.mk
  tests/soter/soter.mk
  tests/test.mk
  tests/themis/themis.mk
  tests/themispp/themispp.mk
  tools/afl/fuzzy.mk
Labels: infrastructure, installation

#448 Use "/usr/local" as default prefix for "make install"
  Makefile
Labels: installation

#452 Always ignore ldconfig failures
  Makefile
Labels: infrastructure, installation

#451 Common Makefile rules
  Makefile
  jni/themis_jni.mk
  src/soter/soter.mk
  src/themis/themis.mk
  src/wrappers/themis/jsthemis/jsthemis.mk
  tests/soter/soter.mk
  tests/test.mk
  tests/themis/themis.mk
  tests/themispp/themispp.mk
Labels: infrastructure, installation

#456 Ignored NIST statistical tests with NO_NIST_STS
  .circleci/config.yml
  tests/soter/soter.mk
  tests/soter/soter_rand_test.c
  tests/test.mk
Labels: infrastructure, tests

#453 Follow GNU conventions for installation
  Makefile
  src/soter/soter.mk
  src/themis/themis.mk
  src/wrappers/themis/themispp/themispp.mk
Labels: infrastructure, installation

#459 Make "all" the default target again
  Makefile
Labels: infrastructure, installation

#458 Explicitly export public API
  Makefile
  Themis.xcodeproj/project.pbxproj
  src/soter/boringssl/soter_asym_cipher.c
  src/soter/boringssl/soter_asym_ka.c
  src/soter/boringssl/soter_hash.c
  src/soter/ed25519/fe.h
  src/soter/ed25519/fe_isnonzero.c
  src/soter/ed25519/fe_neg.c
  src/soter/ed25519/fe_tobytes.c
  src/soter/ed25519/ge.h
  src/soter/ed25519/ge_cmp.c
  src/soter/ed25519/ge_double_scalarmult.c
  src/soter/ed25519/ge_frombytes_no_negate.c
  src/soter/ed25519/ge_p2_to_p3.c
  src/soter/ed25519/ge_p3_sub.c
  src/soter/ed25519/ge_p3_tobytes.c
  src/soter/ed25519/ge_scalarmult.c
  src/soter/ed25519/ge_scalarmult_base.c
  src/soter/ed25519/ge_tobytes.c
  src/soter/ed25519/ge_utils.h
  src/soter/ed25519/gen_rand_32.c
  src/soter/ed25519/sc.h
  src/soter/ed25519/sc_muladd.c
  src/soter/ed25519/sc_reduce.c
  src/soter/openssl/soter_asym_cipher.c
  src/soter/openssl/soter_asym_ka.c
  src/soter/openssl/soter_hash.c
  src/soter/soter.mk
  src/soter/soter_api.h
  src/soter/soter_asym_cipher.h
  src/soter/soter_asym_ka.h
  src/soter/soter_asym_sign.h
  src/soter/soter_container.h
  src/soter/soter_hash.h
  src/soter/soter_hmac.c
  src/soter/soter_hmac.h
  src/soter/soter_kdf.h
  src/soter/soter_rand.h
  src/soter/soter_rsa_key_pair_gen.h
  src/soter/soter_sign.c
  src/soter/soter_sym.h
  src/themis/secure_cell.h
  src/themis/secure_comparator.h
  src/themis/secure_keygen.h
  src/themis/secure_message.h
  src/themis/secure_session.h
  src/themis/themis.mk
  src/themis/themis_api.h
Labels: core

#461 Initial WasmThemis wrapper
  .circleci/config.yml
  Makefile
  src/themis/themis_api.h
  src/wrappers/themis/wasm/.gitignore
  src/wrappers/themis/wasm/.npmignore
  src/wrappers/themis/wasm/LICENSE
  src/wrappers/themis/wasm/README.md
  src/wrappers/themis/wasm/package-lock.json
  src/wrappers/themis/wasm/package.json
  src/wrappers/themis/wasm/runtime_exports.json
  src/wrappers/themis/wasm/src/.gitignore
  src/wrappers/themis/wasm/src/.npmignore
  src/wrappers/themis/wasm/src/index.js
  src/wrappers/themis/wasm/src/secure_keygen.js
  src/wrappers/themis/wasm/src/themis_error.js
  src/wrappers/themis/wasm/test/test.js
  src/wrappers/themis/wasm/wasmthemis.mk
  tests/test.mk
Labels: infrastructure, wasm

#454 ABI-versioned library names
  Makefile
  VERSION
  src/soter/soter.mk
  src/themis/themis.mk
Labels: compatibility, core, installation

#455 Use 'make install' for packaging
  Makefile
Labels: infrastructure, installation

#460 Use dynamic linkage for tests
  Makefile
  tests/soter/soter.mk
  tests/themis/themis.mk
  tests/themispp/themispp.mk
Labels: core, tests

#463 Update iOS/macOS examples [Xcode 10.2, swift 4.2]
  .gitignore
  docs/examples/Themis-server/Obj-C/README.md
  docs/examples/Themis-server/Obj-C/WorkingWithThemisServer.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  docs/examples/Themis-server/Obj-C/WorkingWithThemisServer/WorkingWithThemisServer.xcodeproj/project.pbxproj
  docs/examples/Themis-server/Obj-C/WorkingWithThemisServer/WorkingWithThemisServer.xcodeproj/xcshareddata/xcschemes/WorkingWithThemisServer.xcscheme
  docs/examples/Themis-server/Obj-C/WorkingWithThemisServer/WorkingWithThemisServer/SMessageClient.m
  docs/examples/Themis-server/Obj-C/WorkingWithThemisServer/WorkingWithThemisServer/SSessionClient.m
  docs/examples/Themis-server/swift/README.md
  docs/examples/Themis-server/swift/SwiftThemisServerExample.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  docs/examples/Themis-server/swift/SwiftThemisServerExample/SwiftThemisServerExample.xcodeproj/project.pbxproj
  docs/examples/Themis-server/swift/SwiftThemisServerExample/SwiftThemisServerExample/AppDelegate.swift
  docs/examples/Themis-server/swift/SwiftThemisServerExample/SwiftThemisServerExample/SMessageClient.swift
  docs/examples/Themis-server/swift/SwiftThemisServerExample/SwiftThemisServerExample/SSessionClient.swift
  docs/examples/objc/iOS-CocoaPods/ThemisTest/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/objc/iOS-CocoaPods/ThemisTest/ThemisTest.xcodeproj/xcshareddata/xcschemes/ThemisTest.xcscheme
  docs/examples/swift/iOS-CocoaPods/Podfile
  docs/examples/swift/iOS-CocoaPods/Podfile.lock
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift.xcodeproj/xcshareddata/xcschemes/ThemisSwift.xcscheme
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift/Classes/AppDelegate.swift
  tests/objcthemis/Podfile.lock
  tests/objcthemis/objcthemis.xcodeproj/project.pbxproj
  tests/objcthemis/objcthemis.xcodeproj/xcshareddata/xcschemes/objthemis.xcscheme
  tests/objcthemis/objcthemis.xcodeproj/xcshareddata/xcschemes/objthemis_boring.xcscheme
Labels: ios, macos, tests
