Repository cossacklabs/themis, pull requests merged in 2019-11, with the labels that each got.

#548 Build Themis with sanitizers
  .circleci/config.yml
  Makefile
  src/soter/blacklist-ubsan.txt
  src/soter/soter_container.h
  src/soter/soter_crc32.c
Labels: infrastructure, tests

#544 Update distribution archive
  Makefile
Labels: infrastructure

#551 Improve detection of JDK location for JNI
  CHANGELOG.md
  jni/themis_jni.mk
Labels: W-JavaThemis :coffee:, infrastructure

#552 Link libthemis_jni.so dynamically
  jni/themis_jni.mk
  src/themis/secure_session_t.h
  src/themis/themis_api.h
Labels: W-JavaThemis :coffee:

#554 Fix data alignment issues found by UBSan
  .circleci/config.yml
  Makefile
  src/soter/blacklist-ubsan.txt
  src/soter/ed25519/fe.h
  src/soter/ed25519/fe_cmov.c
  src/soter/ed25519/fe_isnonzero.c
  src/soter/ed25519/fe_mul.c
  src/soter/ed25519/fe_sq.c
  src/soter/ed25519/fe_sq2.c
  src/soter/ed25519/fe_tobytes.c
  src/soter/ed25519/ge_scalarmult_base.c
  src/soter/ed25519/sc_muladd.c
  src/soter/ed25519/sc_reduce.c
  src/soter/soter_container.h
  src/themis/secure_session_message.c
Labels: core

#553 Package Themis JNI library in DEB and RPM
  CHANGELOG.md
  Makefile
  jni/themis_jni.mk
Labels: W-JavaThemis :coffee:, infrastructure

#556 Don't suppress UBSan unless compiling with UBSan
  Makefile
  src/soter/ed25519/fe.h
Labels: core

#555 Fix Secure Comparator in PyThemis on 32-bit
  CHANGELOG.md
  src/wrappers/themis/python/pythemis/scomparator.py
Labels: W-PyThemis :snake:, compatibility

#557 Fix and enable Android tests
  .circleci/config.yml
  CHANGELOG.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/wrappers/themis/java/com/cossacklabs/themis/SecureSocket.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/KeypairGeneratorTest.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SecureCellTest.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SecureCompareTest.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SecureMessageTest.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SecureSessionTest.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SecureSocketTest.java
  third_party/boringssl/build.gradle
Labels: O-Android :robot:, W-JavaThemis :coffee:, infrastructure

#558 Grammar and formatting changes
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  docs/README.md
  docs/examples/README.MD
  docs/examples/rust/README.md
  src/wrappers/themis/python/README.md
  src/wrappers/themis/python/README.rst
  src/wrappers/themis/python/setup.py
  src/wrappers/themis/rust/README.md
  src/wrappers/themis/wasm/README.md
Labels: docs :books:
