Repository cossacklabs/themis, pull requests merged in 2019-05, with the labels that each got.

#466 Fix Clippy warnings
  tools/rust/keygen_tool.rs
Labels: rust

#465 improve keys checks for jsthemis in SecureMessage
  src/wrappers/themis/jsthemis/secure_message.cpp
  tests/jsthemis/test.js
Labels: bug, jsthemis

#467 improve SecureMessage sign/verify examples for iOS
  docs/examples/objc/iOS-Carthage/ThemisTest/AppDelegate.m
  docs/examples/objc/iOS-CocoaPods/ThemisTest/ThemisTest/Classes/AppDelegate.m
  docs/examples/objc/macOS-Carthage/ThemisTest/AppDelegate.m
  docs/examples/swift/iOS-Carthage/Cartfile.resolved
  docs/examples/swift/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-Carthage/ThemisTest/AppDelegate.swift
  docs/examples/swift/iOS-CocoaPods/ThemisSwift.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift/Classes/AppDelegate.swift
  docs/examples/swift/macOS-Carthage/ThemisTest/AppDelegate.swift
Labels: ios, swift

#468 Push jsthemis to npm
  src/wrappers/themis/jsthemis/package.json
Labels: jsthemis

#473 Update Emscripten SDK cleanly
  .circleci/config.yml
Labels: infrastructure

#469 MSYS2 target support
  Makefile
  PKGBUILD.MSYS2
  src/soter/soter.mk
  src/themis/themis.mk
  tests/soter/nist-sts/.gitignore
  tests/soter/soter.mk
  tests/themis/themis.mk
Labels: core, windows

#470 Avoid usage of <arpa/inet.h>
  Themis.xcodeproj/project.pbxproj
  src/soter/boringssl/soter_ec_key.c
  src/soter/boringssl/soter_rsa_key.c
  src/soter/openssl/soter_ec_key.c
  src/soter/openssl/soter_rsa_key.c
  src/soter/portable_endian.h
  src/soter/soter_container.c
  src/soter/soter_container.h
  src/soter/soter_ec_key.h
  src/soter/soter_rsa_key.h
  src/themis/portable_endian.h
  src/themis/secure_keygen.c
  src/themis/secure_session.c
  src/themis/secure_session_message.c
  src/themis/secure_session_serialize.c
  src/themis/secure_session_utils.c
Labels: core, ios, windows

#471 Improve Windows compatibility
  src/soter/ed25519/fe_cmov.c
  src/themis/secure_session.h
  tests/soter/soter_rand_test.c
  tests/themis/themis_secure_session.c
Labels: core, windows

#472 Move SOTER_PRIVATE_API declarations to headers
  src/soter/ed25519/fe.h
  src/soter/ed25519/fe_isnonzero.c
  src/soter/ed25519/fe_neg.c
  src/soter/ed25519/fe_tobytes.c
  src/soter/ed25519/ge.h
  src/soter/ed25519/ge_cmp.c
  src/soter/ed25519/ge_double_scalarmult.c
  src/soter/ed25519/ge_frombytes_no_negate.c
  src/soter/ed25519/ge_p2_to_p3.c
  src/soter/ed25519/ge_p3_sub.c
  src/soter/ed25519/ge_p3_tobytes.c
  src/soter/ed25519/ge_scalarmult.c
  src/soter/ed25519/ge_scalarmult_base.c
  src/soter/ed25519/ge_tobytes.c
  src/soter/ed25519/ge_utils.h
  src/soter/ed25519/gen_rand_32.c
  src/soter/ed25519/sc.h
  src/soter/ed25519/sc_muladd.c
  src/soter/ed25519/sc_reduce.c
  src/soter/soter_hmac.c
  src/soter/soter_t.h
Labels: core

#474 NSIS installer for Windows
  Makefile
  Themis.nsi
Labels: windows

#475 Windows support in JsThemis
  src/wrappers/themis/jsthemis/binding.gyp
Labels: jsthemis, windows
