Repository cossacklabs/themis, pull requests merged in 2020-01, with the labels that each got.

#574 Public PBKDF2 API
  .circleci/config.yml
  CHANGELOG.md
  Themis.xcodeproj/project.pbxproj
  src/soter/boringssl/soter_kdf.c
  src/soter/openssl/soter_kdf.c
  src/soter/soter_kdf.h
  tests/soter/soter.mk
  tests/soter/soter_kdf_test.c
  tests/soter/soter_test.c
  tests/soter/soter_test.h
Labels: core

#576 Fix ODR violation in ThemisPP
  src/wrappers/themis/themispp/secure_keygen.hpp
Labels: W-ThemisPP :crossed_swords:

#581 Update readme for iOS and Rust wrappers
  docs/examples/Themis-server/Obj-C/README.md
  docs/examples/Themis-server/swift/README.md
  src/wrappers/themis/rust/libthemis-sys/README.md
Labels: W-ObjCThemis :art:, W-RustThemis :crab:, W-SwiftThemis :large_orange_diamond:, docs :books:

#578 Hardening compiler flags
  Makefile
Labels: O-Linux :penguin:, core, installation

#580 Automated Themis Core benchmarks
  .circleci/config.yml
  CHANGELOG.md
  Cargo.toml
  benches/README.md
  benches/themis/.gitignore
  benches/themis/Cargo.toml
  benches/themis/README.md
  benches/themis/benches/secure_cell_seal_master_key.rs
Labels: core, infrastructure

#587 Karenswry external readmes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  src/wrappers/themis/ruby/rbthemis.gemspec
  themis.podspec
Labels: docs :books:
