Repository cossacklabs/themis, pull requests merged in 2020-07, with the labels that each got.

#663 Pin emsdk to avoid regression
  .circleci/config.yml
  .github/workflows/integration.yaml
  .github/workflows/test-wasm.yaml
Labels: W-WasmThemis :globe_with_meridians:, infrastructure

#665 Do not cache Emscripten installation
  .circleci/config.yml
Labels: W-WasmThemis :globe_with_meridians:, infrastructure

#664 Stable boilerplate about autogenerated code
  CHANGELOG.md
  src/wrappers/themis/rust/libthemis-sys/bindgen.sh
  src/wrappers/themis/rust/libthemis-sys/src/lib.rs
Labels: W-RustThemis :crab:, infrastructure

#666 Update readme for 0.13
  README.md
Labels: docs :books:

#667 Themis 0.13
  CHANGELOG.md
  ObjCThemis.xcodeproj/project.pbxproj
  PKGBUILD.MSYS2
  Themis.nsi
  Themis.xcodeproj/project.pbxproj
  VERSION
  benches/themis/Cargo.toml
  gradle.properties
  src/wrappers/themis/Obj-C/Themis/Info.plist
  src/wrappers/themis/android/AndroidManifest.xml
  src/wrappers/themis/jsthemis/package-lock.json
  src/wrappers/themis/jsthemis/package.json
  src/wrappers/themis/php/php_themis.h
  src/wrappers/themis/php7/php_themis.h
  src/wrappers/themis/python/PKG-INFO
  src/wrappers/themis/python/setup.py
  src/wrappers/themis/ruby/rbthemis.gemspec
  src/wrappers/themis/rust/CHANGELOG.md
  src/wrappers/themis/rust/Cargo.toml
  src/wrappers/themis/rust/libthemis-src/Cargo.toml
  src/wrappers/themis/rust/libthemis-sys/Cargo.toml
  src/wrappers/themis/wasm/package-lock.json
  src/wrappers/themis/wasm/package.json
  themis.podspec
  third_party/boringssl/AndroidManifest.xml
Labels: release

#668 Require Themis 0.13 in example projects
  docs/examples/Themis-server/Obj-C/Podfile
  docs/examples/Themis-server/swift/Podfile
  docs/examples/objc/iOS-Carthage/Cartfile
  docs/examples/objc/iOS-CocoaPods/Podfile
  docs/examples/objc/macOS-Carthage/Cartfile
  docs/examples/swift/iOS-Carthage/Cartfile
  docs/examples/swift/iOS-CocoaPods/Podfile
  docs/examples/swift/macOS-Carthage/Cartfile
Labels: infrastructure, release

#669 Fix AndroidThemis publishing
  gradle.properties
  src/wrappers/themis/android/build.gradle
  src/wrappers/themis/java/build.gradle
Labels: W-JavaThemis :coffee:, infrastructure

#671 Keep on-demand configuration enabled
  gradle.properties
Labels: O-Android :robot:, W-JavaThemis :coffee:, infrastructure

#672 Themis 0.13.0
  CHANGELOG.md
  ObjCThemis.xcodeproj/project.pbxproj
  PKGBUILD.MSYS2
  README.md
  Themis.nsi
  Themis.xcodeproj/project.pbxproj
  VERSION
  benches/themis/Cargo.toml
  docs/examples/Themis-server/Obj-C/Podfile
  docs/examples/Themis-server/swift/Podfile
  docs/examples/objc/iOS-Carthage/Cartfile
  docs/examples/objc/iOS-CocoaPods/Podfile
  docs/examples/objc/macOS-Carthage/Cartfile
  docs/examples/swift/iOS-Carthage/Cartfile
  docs/examples/swift/iOS-CocoaPods/Podfile
  docs/examples/swift/macOS-Carthage/Cartfile
  gradle.properties
  src/wrappers/themis/Obj-C/Themis/Info.plist
  src/wrappers/themis/android/AndroidManifest.xml
  src/wrappers/themis/android/build.gradle
  src/wrappers/themis/java/build.gradle
  src/wrappers/themis/jsthemis/package-lock.json
  src/wrappers/themis/jsthemis/package.json
  src/wrappers/themis/php/php_themis.h
  src/wrappers/themis/php7/php_themis.h
  src/wrappers/themis/python/PKG-INFO
  src/wrappers/themis/python/setup.py
  src/wrappers/themis/ruby/rbthemis.gemspec
  src/wrappers/themis/rust/CHANGELOG.md
  src/wrappers/themis/rust/Cargo.toml
  src/wrappers/themis/rust/libthemis-src/Cargo.toml
  src/wrappers/themis/rust/libthemis-sys/Cargo.toml
  src/wrappers/themis/wasm/package-lock.json
  src/wrappers/themis/wasm/package.json
  themis.podspec
  third_party/boringssl/AndroidManifest.xml
Labels: release

#673 Update CocoaPods repository
  .github/workflows/test-objc.yaml
Labels: M-CocoaPods, W-ObjCThemis :art:, infrastructure

#674 Update Obj-C/Swift examples to Themis 0.13
  docs/examples/Themis-server/Obj-C/Podfile.lock
  docs/examples/Themis-server/swift/Podfile.lock
  docs/examples/objc/iOS-Carthage/Cartfile.resolved
  docs/examples/objc/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/objc/iOS-Carthage/ThemisTest/AppDelegate.m
  docs/examples/objc/iOS-CocoaPods/Podfile.lock
  docs/examples/objc/iOS-CocoaPods/ThemisTest/ThemisTest/Classes/AppDelegate.m
  docs/examples/objc/macOS-Carthage/Cartfile.resolved
  docs/examples/objc/macOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/objc/macOS-Carthage/ThemisTest/AppDelegate.m
  docs/examples/swift/iOS-Carthage/Cartfile.resolved
  docs/examples/swift/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-Carthage/ThemisTest/AppDelegate.swift
  docs/examples/swift/iOS-CocoaPods/Podfile.lock
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift/Classes/AppDelegate.swift
  docs/examples/swift/macOS-Carthage/Cartfile.resolved
  docs/examples/swift/macOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/macOS-Carthage/ThemisTest/AppDelegate.swift
Labels: M-Carthage, M-CocoaPods, O-iOS :iphone:, O-macOS :computer:, W-ObjCThemis :art:, W-SwiftThemis :large_orange_diamond:

#675 Mention missing breaking change in ThemisPP
  CHANGELOG.md
Labels: W-ThemisPP :crossed_swords:, docs :books:

#676 GoThemis version badge
  README.md
Labels: docs :books:

#677 Avoid overflows on 32-bit systems
  CHANGELOG.md
  gothemis/cell/cell.go
  gothemis/cell/context_imprint.go
  gothemis/cell/seal.go
  gothemis/cell/seal_pw.go
  gothemis/cell/token_protect.go
  gothemis/cell/token_protect_test.go
  gothemis/compare/compare.go
  gothemis/keys/keypair.go
  gothemis/keys/symmetric.go
  gothemis/message/message.go
  gothemis/session/session.go
Labels: W-GoThemis :hamster:, backport, bug

#678 Move static libs and link files into dev packages
  CHANGELOG.md
  Makefile
Labels: O-Linux :penguin:, compatibility, core, infrastructure

#679 Publish source and Javadoc JARs
  CHANGELOG.md
  src/wrappers/themis/android/build.gradle
Labels: O-Android :robot:, W-JavaThemis :coffee:, backport, infrastructure

#681 Include embedded BoringSSL into libsoter.a
  CHANGELOG.md
  scripts/merge-static-libs.sh
  src/soter/soter.mk
  src/wrappers/themis/rust/libthemis-src/themis/scripts
Labels: C-BoringSSL, W-RustThemis :crab:, W-WasmThemis :globe_with_meridians:, core, installation

#682 More accurate package dependencies
  CHANGELOG.md
  Makefile
Labels: O-Linux :penguin:, core, infrastructure, installation

#683 Package Themis Core with BoringSSL
  CHANGELOG.md
  Makefile
Labels: C-BoringSSL, O-Linux :penguin:, core, infrastructure, installation

#684 Add missing OpenSSL includes
  CHANGELOG.md
  ObjCThemis.xcodeproj/project.pbxproj
  src/soter/openssl/soter_ec_key.c
  src/soter/openssl/soter_rsa_common.c
  src/soter/openssl/soter_rsa_key.c
  src/soter/openssl/soter_rsa_key_pair_gen.c
  src/themis/secure_cell_seal_passphrase.c
  src/themis/sym_enc_message.c
Labels: C-OpenSSL, O-iOS :iphone:, O-macOS :computer:, backport, core

#688 Update Swift, ObjC examples code to showcase keygen and passphrase APIs
  CHANGELOG.md
  docs/examples/objc/iOS-Carthage/Cartfile.resolved
  docs/examples/objc/iOS-Carthage/ThemisTest/AppDelegate.m
  docs/examples/objc/iOS-CocoaPods/ThemisTest/ThemisTest/Classes/AppDelegate.m
  docs/examples/objc/iOS-CocoaPods/ThemisTest/ThemisTest/Resources/Base.lproj/LaunchScreen.xib
  docs/examples/objc/macOS-Carthage/Cartfile.resolved
  docs/examples/objc/macOS-Carthage/ThemisTest/AppDelegate.m
  docs/examples/swift/iOS-Carthage/Cartfile.resolved
  docs/examples/swift/iOS-Carthage/ThemisTest/AppDelegate.swift
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift/Classes/AppDelegate.swift
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift/Resources/Base.lproj/LaunchScreen.storyboard
  docs/examples/swift/macOS-Carthage/Cartfile.resolved
  docs/examples/swift/macOS-Carthage/ThemisTest/AppDelegate.swift
  tests/objcthemis/objcthemis.xcodeproj/project.pbxproj
Labels: M-Carthage, M-CocoaPods, O-iOS :iphone:, O-macOS :computer:, W-ObjCThemis :art:, W-SwiftThemis :large_orange_diamond:, enhancement
