Repository cossacklabs/themis, pull requests merged in 2020-06, with the labels that each got.

#646 Make selectable languages in integration tests
  tests/_integration/tests_generator.py
  tests/tools/check_keygen.sh
Labels: infrastructure, tests

#648 Drop Python 2 support
  .circleci/config.yml
  .github/workflows/test-python.yaml
  CHANGELOG.md
  Makefile
  configure
  tests/_integration/tests_generator.py
  tests/test.mk
  tests/tools/check_keygen.sh
Labels: compatibility, infrastructure, tests

#649 Fix path in `themis_jni_install` target
  Makefile
  jni/themis_jni.mk
Labels: bug, infrastructure

#651 Use correct libdir for multiarch Debian
  Makefile
Labels: O-Linux :penguin:, infrastructure, installation

#653 Pin Emscripten toolchain to 1.39.16-fastcomp
  .circleci/config.yml
  .github/workflows/integration.yaml
  .github/workflows/test-wasm.yaml
Labels: W-WasmThemis :globe_with_meridians:, infrastructure

#654 Support Node.js v14
  .circleci/config.yml
  .github/workflows/test-nodejs.yaml
  .github/workflows/test-wasm.yaml
  CHANGELOG.md
Labels: W-JsThemis :lollipop:, W-WasmThemis :globe_with_meridians:, infrastructure

#655 Make Java source ASCII-only
  src/wrappers/themis/java/build.gradle
  src/wrappers/themis/java/com/cossacklabs/themis/SecureCell.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SecureCellSealWithPassphraseTest.java
Labels: W-JavaThemis :coffee:, tests

#656 Improve path-based build triggers
  .github/workflows/test-core.yaml
  .github/workflows/test-wasm.yaml
Labels: infrastructure

#658 Fix Secure Session serialization format
  CHANGELOG.md
  src/themis/secure_session_serialize.c
Labels: W-JavaThemis :coffee:, bug, core

#659 Deprecate Secure Session serialization API
  CHANGELOG.md
  src/wrappers/themis/java/com/cossacklabs/themis/SecureSession.java
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SecureSessionTest.java
Labels: W-JavaThemis :coffee:, compatibility

#660 Update and clean up changelog
  CHANGELOG.md
Labels: docs :books:
