Repository cossacklabs/themis, pull requests merged in 2020-11, with the labels that each got.

#742 Update to Xcode 12.2 recommended settings
  CHANGELOG.md
  Themis.xcodeproj/project.pbxproj
  Themis.xcodeproj/xcshareddata/xcschemes/Test Themis (Swift 4, iOS).xcscheme
  Themis.xcodeproj/xcshareddata/xcschemes/Test Themis (Swift 4, macOS).xcscheme
  Themis.xcodeproj/xcshareddata/xcschemes/Test Themis (Swift 5, iOS).xcscheme
  Themis.xcodeproj/xcshareddata/xcschemes/Test Themis (Swift 5, macOS).xcscheme
  Themis.xcodeproj/xcshareddata/xcschemes/Themis (iOS).xcscheme
  Themis.xcodeproj/xcshareddata/xcschemes/Themis (macOS).xcscheme
  tests/objcthemis/objthemis/SecureMessageTests.m
Labels: M-Carthage, O-iOS :iphone:, O-macOS :computer:, W-ObjCThemis :art:, W-SwiftThemis :large_orange_diamond:, refactoring

#744 Fix code signing issues on macOS with Xcode 12.2
  CHANGELOG.md
  Themis.xcodeproj/project.pbxproj
Labels: M-Carthage, O-macOS :computer:, W-ObjCThemis :art:, W-SwiftThemis :large_orange_diamond:, backport

#745 Themis 0.13.5
  CHANGELOG.md
  Themis.xcodeproj/project.pbxproj
Labels: M-Carthage, O-iOS :iphone:, O-macOS :computer:, W-ObjCThemis :art:, W-SwiftThemis :large_orange_diamond:, release

#746 Slightly update README
  README.md
Labels: docs :books:

#747 Merge branch 'release/0.13' into stable
  CHANGELOG.md
  Themis.xcodeproj/project.pbxproj
Labels: release

#748 Merge branch 'stable' into master
  CHANGELOG.md
  Themis.xcodeproj/project.pbxproj
Labels: release

#749 Use environment files in GitHub Actions
  .github/workflows/integration.yaml
  .github/workflows/test-objc.yaml
  .github/workflows/test-ruby.yaml
Labels: infrastructure

#751 Use environment files in GitHub Actions
  .github/workflows/integration.yaml
  .github/workflows/test-objc.yaml
  .github/workflows/test-ruby.yaml
Labels: backport, infrastructure

#750 Dynamic linkage for CocoaPods
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: M-Carthage, M-CocoaPods, O-iOS :iphone:, O-macOS :computer:, W-ObjCThemis :art:, W-SwiftThemis :large_orange_diamond:, dependencies

#752 Themis 0.13.6
  CHANGELOG.md
  Cartfile
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: release

#753 Merge branch 'release/0.13' into stable
  .github/workflows/integration.yaml
  .github/workflows/test-objc.yaml
  .github/workflows/test-ruby.yaml
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: release

#754 Merge branch 'stable' into master
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: release

#756 Add `tests` directory for `soter_test` target
  CMakeLists.txt
Labels: infrastructure, tests

#755 Measure test coverage with GitHub Actions
  .circleci/config.yml
  .github/workflows/test-core.yaml
  CHANGELOG.md
Labels: infrastructure, tests

#758 Use new trait order in generated code
  src/wrappers/themis/rust/libthemis-sys/src/lib.rs
Labels: W-RustThemis :crab:, infrastructure

#759 Move public Themis headers to "include" directory
  CHANGELOG.md
  Makefile
  Themis.xcodeproj/project.pbxproj
  include/soter/soter.h
  include/soter/soter_api.h
  include/soter/soter_asym_cipher.h
  include/soter/soter_asym_ka.h
  include/soter/soter_asym_sign.h
  include/soter/soter_error.h
  include/soter/soter_hash.h
  include/soter/soter_hmac.h
  include/soter/soter_kdf.h
  include/soter/soter_rand.h
  include/soter/soter_rsa_key_pair_gen.h
  include/soter/soter_sym.h
  include/soter/soter_wipe.h
  include/themis/secure_cell.h
  include/themis/secure_comparator.h
  include/themis/secure_keygen.h
  include/themis/secure_message.h
  include/themis/secure_session.h
  include/themis/themis.h
  include/themis/themis_api.h
  include/themis/themis_error.h
  jni/Android.mk
  src/soter/openssl/soter_rsa_key_pair_gen.c
  src/soter/soter.mk
  src/themis/secure_session_peer.h
  src/themis/secure_session_t.h
  src/themis/secure_session_utils.h
  src/themis/themis.mk
  src/wrappers/themis/rust/libthemis-sys/bindgen.sh
  src/wrappers/themis/rust/libthemis-sys/src/lib.rs
  tests/soter/soter_test.h
  themis.podspec
Labels: compatibility, core, installation

#757 Replace the obsolete OpenSSL functions EVP_{De,En}cryptFinal
  src/soter/openssl/soter_sym.c
Labels: core
