Repository cossacklabs/themis, pull requests merged in 2021-04, with the labels that each got.

#797 Set timeouts on some CI jobs
  .github/workflows/test-java.yaml
  .github/workflows/test-python.yaml
Labels: W-JavaThemis :coffee:, W-PyThemis :snake:, infrastructure

#792 Migrate wasm-themis to TypeScript
  src/wrappers/themis/wasm/.gitignore
  src/wrappers/themis/wasm/emscripten/exports.json
  src/wrappers/themis/wasm/package-lock.json
  src/wrappers/themis/wasm/package.json
  src/wrappers/themis/wasm/src/.gitignore
  src/wrappers/themis/wasm/src/context.ts
  src/wrappers/themis/wasm/src/index.js
  src/wrappers/themis/wasm/src/index.ts
  src/wrappers/themis/wasm/src/libthemis.d.ts
  src/wrappers/themis/wasm/src/secure_cell.ts
  src/wrappers/themis/wasm/src/secure_cell_context_imprint.js
  src/wrappers/themis/wasm/src/secure_cell_context_imprint.ts
  src/wrappers/themis/wasm/src/secure_cell_seal.js
  src/wrappers/themis/wasm/src/secure_cell_seal.ts
  src/wrappers/themis/wasm/src/secure_cell_token_protect.js
  src/wrappers/themis/wasm/src/secure_cell_token_protect.ts
  src/wrappers/themis/wasm/src/secure_comparator.js
  src/wrappers/themis/wasm/src/secure_comparator.ts
  src/wrappers/themis/wasm/src/secure_keygen.js
  src/wrappers/themis/wasm/src/secure_keygen.ts
  src/wrappers/themis/wasm/src/secure_message.js
  src/wrappers/themis/wasm/src/secure_message.ts
  src/wrappers/themis/wasm/src/secure_session.js
  src/wrappers/themis/wasm/src/secure_session.ts
  src/wrappers/themis/wasm/src/themis_error.js
  src/wrappers/themis/wasm/src/themis_error.ts
  src/wrappers/themis/wasm/src/utils.js
  src/wrappers/themis/wasm/src/utils.ts
  src/wrappers/themis/wasm/test/test.js
  src/wrappers/themis/wasm/tsconfig.json
  src/wrappers/themis/wasm/wasmthemis.mk
  tools/js/wasm-themis/keygen.js
  tools/js/wasm-themis/scell_context_string_echo.js
  tools/js/wasm-themis/scell_seal_string_echo.js
  tools/js/wasm-themis/scell_seal_string_echo_pw.js
  tools/js/wasm-themis/scell_token_string_echo.js
  tools/js/wasm-themis/smessage_encryption.js
Labels: W-WasmThemis :globe_with_meridians:

#799 Update zeroize to `1`
  CHANGELOG.md
  src/wrappers/themis/rust/Cargo.toml
Labels: W-RustThemis :crab:, dependencies

#800 Update zeroize to `1` (on stable)
  src/wrappers/themis/rust/Cargo.toml
Labels: W-RustThemis :crab:, backport, dependencies

#801 Test {Js,Wasm}Themis with Node.js v16
  .github/workflows/test-nodejs.yaml
  .github/workflows/test-wasm.yaml
  CHANGELOG.md
Labels: W-JsThemis :lollipop:, W-WasmThemis :globe_with_meridians:, infrastructure

#789 Add SPM support with XCF
  CHANGELOG.md
  Package.swift
  Themis.xcodeproj/project.pbxproj
  scripts/create_xcframeworks.sh
Labels: M-SPM, W-SwiftThemis :large_orange_diamond:
