Repository cossacklabs/themis, pull requests merged in 2021-05, with the labels that each got.

#814 Update npm lockfiles
  src/wrappers/themis/jsthemis/package-lock.json
  src/wrappers/themis/wasm/package-lock.json
Labels: W-JsThemis :lollipop:, W-WasmThemis :globe_with_meridians:, dependencies

#813 Assimilate Android example project
  .github/workflows/test-java.yaml
  CHANGELOG.md
  docs/examples/android/.gitignore
  docs/examples/android/app/.gitignore
  docs/examples/android/app/build.gradle
  docs/examples/android/app/proguard-rules.pro
  docs/examples/android/app/src/main/AndroidManifest.xml
  docs/examples/android/app/src/main/java/com/cossacklabs/themis/android/example/HttpCallback.kt
  docs/examples/android/app/src/main/java/com/cossacklabs/themis/android/example/HttpClient.kt
  docs/examples/android/app/src/main/java/com/cossacklabs/themis/android/example/MainActivitySecureCell.kt
  docs/examples/android/app/src/main/java/com/cossacklabs/themis/android/example/MainActivitySecureMessage.kt
  docs/examples/android/app/src/main/java/com/cossacklabs/themis/android/example/MainActivitySecureSession.kt
  docs/examples/android/app/src/main/java/com/cossacklabs/themis/android/example/SecMessageExampleClient.kt
  docs/examples/android/app/src/main/java/com/cossacklabs/themis/android/example/SecSessionExampleClient.kt
  docs/examples/android/app/src/main/res/layout/activity_main.xml
  docs/examples/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  docs/examples/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  docs/examples/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  docs/examples/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  docs/examples/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  docs/examples/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  docs/examples/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  docs/examples/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  docs/examples/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  docs/examples/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  docs/examples/android/app/src/main/res/values/colors.xml
  docs/examples/android/app/src/main/res/values/strings.xml
  docs/examples/android/app/src/main/res/values/styles.xml
  docs/examples/android/build.gradle
  docs/examples/android/gradle.properties
  docs/examples/android/gradle/wrapper/gradle-wrapper.jar
  docs/examples/android/gradle/wrapper/gradle-wrapper.properties
  docs/examples/android/gradlew
  docs/examples/android/gradlew.bat
  docs/examples/android/settings.gradle
Labels: O-Android :robot:, docs :books:, infrastructure

#816 Assimilate Java example project
  .github/workflows/test-java.yaml
  CHANGELOG.md
  docs/examples/java/app/build.gradle
  docs/examples/java/app/src/SMessageClient.java
  docs/examples/java/app/src/SSessionClient.java
  docs/examples/java/app/src/main.java
  docs/examples/java/build.gradle
  docs/examples/java/gradle/wrapper/gradle-wrapper.jar
  docs/examples/java/gradle/wrapper/gradle-wrapper.properties
  docs/examples/java/gradlew
  docs/examples/java/gradlew.bat
  docs/examples/java/settings.gradle
Labels: W-JavaThemis :coffee:, docs :books:, infrastructure

#810 Build Themis + BoringSSL with Xcode
  .github/workflows/test-objc.yaml
  Themis.xcodeproj/project.pbxproj
  Themis.xcodeproj/xcshareddata/xcschemes/Test Themis (BoringSSL, Swift 5, iOS).xcscheme
  Themis.xcodeproj/xcshareddata/xcschemes/Test Themis (BoringSSL, Swift 5, macOS).xcscheme
Labels: C-BoringSSL, O-iOS :iphone:, O-macOS :computer:

#823 Updated Carthage examples to use XCF
  .github/workflows/test-objc.yaml
  CHANGELOG.md
  docs/examples/objc/iOS-Carthage/Cartfile
  docs/examples/objc/iOS-Carthage/Cartfile.resolved
  docs/examples/objc/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/objc/macOS-Carthage/Cartfile
  docs/examples/objc/macOS-Carthage/Cartfile.resolved
  docs/examples/objc/macOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-Carthage/Cartfile
  docs/examples/swift/iOS-Carthage/Cartfile.resolved
  docs/examples/swift/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/macOS-Carthage/Cartfile
  docs/examples/swift/macOS-Carthage/Cartfile.resolved
  docs/examples/swift/macOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
Labels: M-Carthage, O-iOS :iphone:, O-macOS :computer:

#824 Unbreak Android build
  .github/workflows/test-java.yaml
Labels: O-Android :robot:, infrastructure

#825 BoringSSL support for XCFramework builds
  scripts/create_xcframeworks.sh
Labels: C-BoringSSL, O-iOS :iphone:, O-macOS :computer:

#829 Update Carthage examples to unbreak tests
  .github/workflows/test-objc.yaml
  CHANGELOG.md
  docs/examples/objc/iOS-Carthage/Cartfile
  docs/examples/objc/iOS-Carthage/Cartfile.resolved
  docs/examples/objc/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/100.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/1024.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/114.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/120.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/144.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/152.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/167.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/180.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/20.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/29.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/40.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/50.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/57.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/58.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/60.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/72.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/76.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/80.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/87.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/Contents.json
  docs/examples/objc/macOS-Carthage/Cartfile
  docs/examples/objc/macOS-Carthage/Cartfile.resolved
  docs/examples/objc/macOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-Carthage/Cartfile
  docs/examples/swift/iOS-Carthage/Cartfile.resolved
  docs/examples/swift/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-Carthage/ThemisTest/AppDelegate.swift
  docs/examples/swift/iOS-Carthage/ThemisTest/Base.lproj/Main.storyboard
  docs/examples/swift/macOS-Carthage/Cartfile
  docs/examples/swift/macOS-Carthage/Cartfile.resolved
  docs/examples/swift/macOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
Labels: M-Carthage, O-iOS :iphone:

#828 Themis CocoaPods now support CLOpenSSL-XCF
  CHANGELOG.md
  Package.swift
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: M-CocoaPods, O-iOS :iphone:

#830 Release process: Merge 0.13.10 to stable
  .github/workflows/test-objc.yaml
  CHANGELOG.md
  Package.swift
  Themis.xcodeproj/project.pbxproj
  docs/examples/objc/iOS-Carthage/Cartfile
  docs/examples/objc/iOS-Carthage/Cartfile.resolved
  docs/examples/objc/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/100.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/1024.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/114.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/120.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/144.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/152.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/167.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/180.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/20.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/29.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/40.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/50.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/57.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/58.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/60.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/72.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/76.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/80.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/87.png
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  docs/examples/objc/iOS-Carthage/ThemisTest/Assets.xcassets/Contents.json
  docs/examples/objc/macOS-Carthage/Cartfile
  docs/examples/objc/macOS-Carthage/Cartfile.resolved
  docs/examples/objc/macOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-Carthage/Cartfile
  docs/examples/swift/iOS-Carthage/Cartfile.resolved
  docs/examples/swift/iOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-Carthage/ThemisTest/AppDelegate.swift
  docs/examples/swift/iOS-Carthage/ThemisTest/Base.lproj/Main.storyboard
  docs/examples/swift/macOS-Carthage/Cartfile
  docs/examples/swift/macOS-Carthage/Cartfile.resolved
  docs/examples/swift/macOS-Carthage/ThemisTest.xcodeproj/project.pbxproj
  themis.podspec
Labels: M-Carthage, M-CocoaPods, O-iOS :iphone:

#831 Release process: merge 0.13.10 to master
  CHANGELOG.md
  Package.swift
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: M-CocoaPods, O-iOS :iphone:

#833 Unbreak Android build (on release/0.13)
  .github/workflows/test-java.yaml
Labels: O-Android :robot:, backport, infrastructure

#834 update CocoaPods examples with Themis 0.13.10
  CHANGELOG.md
  docs/examples/objc/iOS-CocoaPods/Podfile
  docs/examples/objc/iOS-CocoaPods/Podfile.lock
  docs/examples/objc/iOS-CocoaPods/ThemisTest/ThemisTest.xcodeproj/project.pbxproj
  docs/examples/swift/iOS-CocoaPods/Podfile
  docs/examples/swift/iOS-CocoaPods/Podfile.lock
  docs/examples/swift/iOS-CocoaPods/ThemisSwift/ThemisSwift.xcodeproj/project.pbxproj
Labels: M-CocoaPods, O-iOS :iphone:

#835 Unbreak PyThemis installation on CircleCI
  .circleci/config.yml
Labels: infrastructure

#836 Merge CI fixes: `release/0.13` => `stable`
  .circleci/config.yml
  .github/workflows/test-java.yaml
Labels: infrastructure

#838 Work around Carthage braindeath
  .github/workflows/test-objc.yaml
Labels: M-Carthage, infrastructure

#837 Use Ninja for BoringSSL if available
  .github/workflows/test-core.yaml
  .github/workflows/test-wasm.yaml
  CHANGELOG.md
  configure
  src/soter/boringssl/soter.mk
Labels: infrastructure
