Repository cossacklabs/themis, pull requests merged in 2021-07, with the labels that each got.

#852 Adjust WasmThemis 0.13.11 release date
  CHANGELOG.md
Labels: docs :books:, release

#851 WasmThemis example project with webpack
  docs/examples/wasm/webpack/.gitignore
  docs/examples/wasm/webpack/README.md
  docs/examples/wasm/webpack/dist/favicon.png
  docs/examples/wasm/webpack/dist/main.css
  docs/examples/wasm/webpack/package.json
  docs/examples/wasm/webpack/src/base64.js
  docs/examples/wasm/webpack/src/index.html
  docs/examples/wasm/webpack/src/index.js
  docs/examples/wasm/webpack/src/secure-cell.js
  docs/examples/wasm/webpack/src/utf8.js
  docs/examples/wasm/webpack/webpack.config.js
Labels: W-WasmThemis :globe_with_meridians:, docs :books:

#855 Merge branch `release/0.13` into `stable`
  CHANGELOG.md
  src/wrappers/themis/wasm/package-lock.json
  src/wrappers/themis/wasm/package.json
  src/wrappers/themis/wasm/src/utils.js
Labels: release

#856 Merge branch `stable` into `master`
  CHANGELOG.md
  src/wrappers/themis/wasm/package-lock.json
  src/wrappers/themis/wasm/package.json
Labels: release

#853 Bring back `undefined` into TypeError tests
  src/wrappers/themis/wasm/test/test.js
Labels: W-WasmThemis :globe_with_meridians:, tests

#854 Bring back `initialized` promise
  CHANGELOG.md
  docs/examples/wasm/node.js-es5/secure_cell.js
  docs/examples/wasm/node.js-es5/secure_comparator_client.js
  docs/examples/wasm/node.js-es5/secure_comparator_server.js
  docs/examples/wasm/node.js-es5/secure_keygen.js
  docs/examples/wasm/node.js-es5/secure_message.js
  docs/examples/wasm/node.js-es5/secure_session_client.js
  docs/examples/wasm/node.js-es5/secure_session_server.js
  docs/examples/wasm/node.js-es6/secure_cell.mjs
  docs/examples/wasm/node.js-es6/secure_comparator_client.mjs
  docs/examples/wasm/node.js-es6/secure_comparator_server.mjs
  docs/examples/wasm/node.js-es6/secure_keygen.mjs
  docs/examples/wasm/node.js-es6/secure_message.mjs
  docs/examples/wasm/node.js-es6/secure_session_client.mjs
  docs/examples/wasm/node.js-es6/secure_session_server.mjs
  docs/examples/wasm/webpack/src/index.js
  src/wrappers/themis/wasm/package.json
  src/wrappers/themis/wasm/src/index.ts
  src/wrappers/themis/wasm/test/initialization/README.md
  src/wrappers/themis/wasm/test/initialization/initialize-path.js
  src/wrappers/themis/wasm/test/initialization/initialize.js
  src/wrappers/themis/wasm/test/initialization/initialized.js
  src/wrappers/themis/wasm/test/test.js
  tools/js/wasm-themis/keygen.js
  tools/js/wasm-themis/keygen.mjs
  tools/js/wasm-themis/scell_context_string_echo.js
  tools/js/wasm-themis/scell_context_string_echo.mjs
  tools/js/wasm-themis/scell_seal_string_echo.js
  tools/js/wasm-themis/scell_seal_string_echo.mjs
  tools/js/wasm-themis/scell_seal_string_echo_pw.js
  tools/js/wasm-themis/scell_seal_string_echo_pw.mjs
  tools/js/wasm-themis/scell_token_string_echo.js
  tools/js/wasm-themis/scell_token_string_echo.mjs
  tools/js/wasm-themis/smessage_encryption.js
  tools/js/wasm-themis/smessage_encryption.mjs
Labels: W-WasmThemis :globe_with_meridians:

#857 Allow calling `initialize()` only once
  CHANGELOG.md
  src/wrappers/themis/wasm/src/index.ts
  src/wrappers/themis/wasm/test/initialization/initialize-path.js
  src/wrappers/themis/wasm/test/initialization/initialize.js
  src/wrappers/themis/wasm/test/initialization/initialized.js
Labels: W-WasmThemis :globe_with_meridians:

#858 Make keys `Uint8Arrays` again (by killing ES5 support)
  docs/examples/wasm/node.js-es5/secure_keygen.js
  docs/examples/wasm/node.js-es6/secure_keygen.mjs
  docs/examples/wasm/webpack/src/secure-cell.js
  src/wrappers/themis/wasm/package.json
  src/wrappers/themis/wasm/src/secure_keygen.ts
  src/wrappers/themis/wasm/src/secure_message.ts
  src/wrappers/themis/wasm/src/secure_session.ts
  src/wrappers/themis/wasm/test/test.js
  src/wrappers/themis/wasm/tsconfig.json
  tools/js/wasm-themis/keygen.js
  tools/js/wasm-themis/keygen.mjs
Labels: W-WasmThemis :globe_with_meridians:

#859 Keep a copy of libthemis.wasm in `src`
  src/wrappers/themis/wasm/package.json
Labels: W-WasmThemis :globe_with_meridians:

#860 Provide default export from the main module
  src/wrappers/themis/wasm/src/index.ts
  src/wrappers/themis/wasm/src/secure_cell.ts
Labels: W-WasmThemis :globe_with_meridians:

#861 Announce TypeScript support for WasmThemis
  CHANGELOG.md
Labels: W-WasmThemis :globe_with_meridians:, docs :books:

#862 Merge branch `wasm-typescript`
  CHANGELOG.md
  src/wrappers/themis/wasm/.gitignore
  src/wrappers/themis/wasm/emscripten/exports.json
  src/wrappers/themis/wasm/package-lock.json
  src/wrappers/themis/wasm/package.json
  src/wrappers/themis/wasm/src/.gitignore
  src/wrappers/themis/wasm/src/context.ts
  src/wrappers/themis/wasm/src/index.js
  src/wrappers/themis/wasm/src/index.ts
  src/wrappers/themis/wasm/src/libthemis.d.ts
  src/wrappers/themis/wasm/src/secure_cell.js
  src/wrappers/themis/wasm/src/secure_cell_context_imprint.js
  src/wrappers/themis/wasm/src/secure_cell_context_imprint.ts
  src/wrappers/themis/wasm/src/secure_cell_seal.js
  src/wrappers/themis/wasm/src/secure_cell_seal.ts
  src/wrappers/themis/wasm/src/secure_cell_token_protect.js
  src/wrappers/themis/wasm/src/secure_cell_token_protect.ts
  src/wrappers/themis/wasm/src/secure_comparator.js
  src/wrappers/themis/wasm/src/secure_comparator.ts
  src/wrappers/themis/wasm/src/secure_keygen.js
  src/wrappers/themis/wasm/src/secure_keygen.ts
  src/wrappers/themis/wasm/src/secure_message.js
  src/wrappers/themis/wasm/src/secure_message.ts
  src/wrappers/themis/wasm/src/secure_session.js
  src/wrappers/themis/wasm/src/secure_session.ts
  src/wrappers/themis/wasm/src/themis_error.js
  src/wrappers/themis/wasm/src/themis_error.ts
  src/wrappers/themis/wasm/src/utils.js
  src/wrappers/themis/wasm/src/utils.ts
  src/wrappers/themis/wasm/test/initialization/README.md
  src/wrappers/themis/wasm/test/initialization/initialize-path.js
  src/wrappers/themis/wasm/test/initialization/initialize.js
  src/wrappers/themis/wasm/test/initialization/initialized.js
  src/wrappers/themis/wasm/test/test.js
  src/wrappers/themis/wasm/tsconfig.json
  src/wrappers/themis/wasm/wasmthemis.mk
Labels: W-WasmThemis :globe_with_meridians:

#844 Move reference implementation into the monorepo
  .github/workflows/test-go.yaml
  CODEOWNERS
  docs/reference-implementation/README.md
  docs/reference-implementation/go.mod
  docs/reference-implementation/soter/soter-alg.go
  docs/reference-implementation/soter/soter-alg_test.go
  docs/reference-implementation/soter/soter-container.go
  docs/reference-implementation/soter/soter-container_test.go
  docs/reference-implementation/soter/soter-kdf.go
  docs/reference-implementation/soter/soter-kdf_test.go
  tests/reference-implementation/go.mod
  tests/reference-implementation/soter/algorithm_ID_test.go
  tests/reference-implementation/soter/container_test.go
  tests/reference-implementation/soter/soter_KDF.go
  tests/reference-implementation/soter/soter_KDF_test.go
  tests/reference-implementation/vendor/github.com/cossacklabs/themis/docs/reference-implementation
  tests/reference-implementation/vendor/github.com/cossacklabs/themis/gothemis
Labels: W-GoThemis :hamster:, docs :books:, infrastructure

#865 M1 simulator fix: Removed arm64 from excluded archs
  CHANGELOG.md
  Package.swift
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: M-Carthage, M-CocoaPods, M-SPM, M1, O-iOS :iphone:

#866 Release process: M1 simulator fix: Removed arm64 from excluded archs (#865)
  CHANGELOG.md
  Package.swift
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: M-Carthage, M-CocoaPods, M-SPM, M1, O-iOS :iphone:

#867 Release process: M1 simulator fix: Removed arm64 from excluded archs (#865)
  CHANGELOG.md
  Package.swift
  Themis.xcodeproj/project.pbxproj
  themis.podspec
Labels: M-Carthage, M-CocoaPods, M-SPM, M1, O-iOS :iphone:
