Repository cossacklabs/themis, pull requests merged in 2021-02, with the labels that each got.

#767 Test Secure Message signature length weirdness
  tests/themis/themis_seccure_message.c
Labels: core, tests

#769 Unbreak Criterion's HTML reports
  .circleci/config.yml
  .github/workflows/test-core.yaml
  benches/themis/Cargo.toml
Labels: backport, infrastructure

#771 Run examples only with Python 3
  .github/workflows/test-python.yaml
Labels: W-PyThemis :snake:, backport, infrastructure

#772 Use new trait order in generated code
  src/wrappers/themis/rust/libthemis-sys/src/lib.rs
Labels: W-RustThemis :crab:, backport, infrastructure

#773 Update code style checking job to Ubuntu 20.04
  .github/workflows/code-style.yaml
Labels: backport, infrastructure

#770 Migrate to "afl++" from "afl"
  .github/workflows/test-core.yaml
  tools/afl/fuzzy.mk
Labels: backport, infrastructure

#768 Update misc. links and READMEs
  CONTRIBUTING.md
  benches/themis/README.md
  docs/examples/README.MD
  docs/examples/Themis-server/Obj-C/README.md
  docs/examples/Themis-server/swift/README.md
  docs/examples/Themis-server/swift/SwiftThemisServerExample/SwiftThemisServerExample/AppDelegate.swift
  docs/examples/Themis-server/swift/SwiftThemisServerExample/SwiftThemisServerExample/SMessageClient.swift
  docs/examples/Themis-server/swift/SwiftThemisServerExample/SwiftThemisServerExample/SSessionClient.swift
  docs/examples/rust/README.md
  gothemis/cell/cell.go
  gothemis/cell/context_imprint.go
  gothemis/cell/seal.go
  gothemis/cell/seal_pw.go
  gothemis/cell/token_protect.go
  src/wrappers/themis/Obj-C/objcthemis/scell.h
  src/wrappers/themis/Obj-C/objcthemis/scell_context_imprint.h
  src/wrappers/themis/Obj-C/objcthemis/scell_seal.h
  src/wrappers/themis/Obj-C/objcthemis/scell_token.h
  src/wrappers/themis/java/com/cossacklabs/themis/SecureCell.java
  src/wrappers/themis/jsthemis/README.md
  src/wrappers/themis/python/README.md
  src/wrappers/themis/rust/README.md
  src/wrappers/themis/rust/src/keygen.rs
  src/wrappers/themis/rust/src/keys.rs
  src/wrappers/themis/rust/src/secure_cell.rs
  src/wrappers/themis/rust/src/secure_message.rs
  src/wrappers/themis/wasm/README.md
  tests/test.mk
  tools/afl/README.md
Labels: W-GoThemis :hamster:, W-JavaThemis :coffee:, W-JsThemis :lollipop:, W-ObjCThemis :art:, W-PHPThemis :elephant:, W-PyThemis :snake:, W-RbThemis :diamonds:, W-RustThemis :crab:, W-SwiftThemis :large_orange_diamond:, W-ThemisPP :crossed_swords:, W-WasmThemis :globe_with_meridians:, docs :books:

#774 Test Secure Message weirdness correctly
  tests/themis/themis_seccure_message.c
Labels: core, tests

#775 Optimize Secure Message signature length
  CHANGELOG.md
  gothemis/message/message.go
  gothemis/message/message_test.go
  src/wrappers/themis/themispp/secure_message.hpp
  tests/themispp/secure_message_test.hpp
Labels: W-GoThemis :hamster:, W-ThemisPP :crossed_swords:

#777 Optimize Secure Message length
  CHANGELOG.md
  jni/themis_message.c
  tests/themis/wrappers/android/com/cossacklabs/themis/test/SecureMessageTest.java
Labels: W-JavaThemis :coffee:

#780 Update Emscripten 2.0.9 => 2.0.13
  .github/workflows/integration.yaml
  .github/workflows/test-wasm.yaml
Labels: W-WasmThemis :globe_with_meridians:, infrastructure

#783 Remove TextEncoder polyfill (#779)
  src/wrappers/themis/wasm/package-lock.json
  src/wrappers/themis/wasm/package.json
  src/wrappers/themis/wasm/src/utils.js
Labels: W-WasmThemis :globe_with_meridians:

#782 Use correct Javadoc syntax
  src/wrappers/themis/java/com/cossacklabs/themis/KeypairGenerator.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureCell.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureCellData.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureMessage.java
  src/wrappers/themis/java/com/cossacklabs/themis/SecureSession.java
Labels: W-JavaThemis :coffee:, docs :books:

#781 Decrease limit for KDF execution time in test
  src/wrappers/themis/wasm/test/test.js
Labels: W-WasmThemis :globe_with_meridians:, tests
